---
- name: Install web performance test tools including wrk, weighttp
  hosts: WebClientX86
  remote_user: estuaryapp
  become: yes
  become_method: sudo
  roles:
    - wrk
    - weighttp

- name: Install Nginx web server on ARM64Server
  hosts: WebServerD05
  remote_user: estuaryapp
  become: yes
  become_method: sudo
  roles:
    - estuaryrepo
    - nginx
    - php-fpm

- name: Install Nginx web server on X86Server
  hosts: WebServerX86
  remote_user: estuaryapp
  become: yes
  become_method: sudo
  roles:
    - nginx
    - php-fpm

